version: '3.3'
#for IP see services' log "wordpress"  (172.19.0.2)
#look for
# " apache2: Could not reliably determine the server's fully qualified domain name, using x.x.x.x "
services:

  wordpress:
    image: fchipi/wordpress-xdebug:v1.5.0
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes: 
      - ./html:/var/www/html/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
   db_data:



